name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose && cargo test --verbose --features=arc && cargo test --verbose --features=f64 && cargo test --verbose --features=bigint && cargo test --verbose --features=bigint,f64
